version: 1.0.{build}
install:
- ps: >-
    (New-Object Net.WebClient).DownloadFile('http://downloads.arduino.cc/arduino-1.6.11-windows.zip', 'C:\projects\arduino.zip')
    Expand-Archive C:\projects\arduino.zip -dest C:\projects\arduino\

    (New-Object Net.WebClient).DownloadFile('http://downloads.arduino.cc/libraries/NicoHood/HID_Project-2.4.3.zip', 'C:\projects\hidproject.zip')
    Expand-Archive C:\projects\hidproject.zip -dest C:\projects\hidproject\
    Copy-Item 'C:\projects\hidproject\HID_Project-2.4.3' 'C:\projects\arduino\arduino-1.6.11\libraries\HID-Project' -recurse
build_script:
- cmd: >-
    cd C:\projects\arduino\arduino-1.6.11
    arduino_debug.exe --verify --board arduino:avr:leonardo --verbose-build C:\projects\Temp2IoT\src\Temp2IoT\Temp2IoT.ino
